[theme]
primaryColor = "#7B1FA2"
backgroundColor = "#4527A0"
secondaryBackgroundColor = "rgba(255, 255, 255, 0.1)"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = true

# Hier können weitere Streamlit-Konfigurationen hinzugefügt werden 