[openai]
api_key = "" # Hier deinen API-Key eintragen

# Diese Datei dient als Platzhalter für die Streamlit Cloud
# Du musst deinen tatsächlichen API-Key in den Streamlit Cloud Einstellungen hinterlegen 