# Vorlage für die Streamlit Cloud Secrets
# Kopiere diese Datei als "secrets.toml" (lokal) oder füge den Inhalt in die Streamlit Cloud Secrets ein

[openai]
api_key = "dein-openai-api-key"

[general]
# Hier können weitere Konfigurationseinstellungen hinzugefügt werden
default_template = "Klassisch"
show_extracted_text = false 